#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#drumkit:
#    path: /drumkit
#    controller: App\Controller\DefaultController::drumkit

#pierre:
#    path: /pierre
#    controller: App\Controller\DefaultController::pierre
